# Generated by Django 6.1.1 on 2026-09-19 11:26

import cards.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFCCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_uid', models.CharField(max_length=50, unique=True)),
                ('public_token', models.CharField(default=cards.models.generate_public_token, editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='UNASSIGNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfc_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
