# Generated by Django 6.1.1 on 2026-09-19 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nfccard',
            name='programmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfccard',
            name='programmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programmed_nfc_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='status',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned'), ('PROGRAMMED', 'Programmed'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='UNASSIGNED', max_length=20),
        ),
    ]
